version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-types: "production"
        patterns:
          - "*"
      devDependencies:
        dependency-types: "development"
        patterns:
          - "*"
