name: Delete Vercel Deployment on PR Close

on:
  pull_request:
    types:
      - closed

jobs:
  delete-deployment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.pull_request.merged == false

    steps:
      - name: Extract PR Number
        id: pr-info
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Fetch Vercel Deployments
        id: fetch-deployments
        run: |
          curl -s -G -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments" \
            --data-urlencode projectId=${{ secrets.VERCEL_PROJECT_ID }} \
            --data-urlencode meta-pr-number=${{ env.PR_NUMBER }} > deployments.json
          cat deployments.json
          export DEPLOYMENT_ID=$(jq -r '.deployments[0].uid' deployments.json)
          echo $DEPLOYMENT_ID
          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Delete Deployment
        if: env.DEPLOYMENT_ID != ''
        run: |
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v13/deployments/${{ env.DEPLOYMENT_ID }}"

      - name: Output Result
        if: env.DEPLOYMENT_ID == ''
        run: echo "No matching deployment found for PR #${{ env.PR_NUMBER }}"
