name: Delete Vercel Deployment on PR Close

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  delete-deployment:
    if: github.event.pull_request.merged == true || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call the delete script
        run: |
          bash ./scripts/delete-preview-deployment.sh ${{ github.event.number }}
