name: Delete Vercel Deployment on PR Close

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  delete-deployment:
    if: github.event.pull_request.merged == true || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch_name
        shell: bash
        run: echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Call the delete script
        run: |
          bash ./scripts/delete-preview-deployment.sh ${{ steps.extract_branch_name.outputs.branch_name }}
