name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Unit Test
        run: pnpm run test